[script:dig_config]
match = /dig_config
handler = dig_config.DIGConfig
requireAuthentication = true
output_modes = json
python.version = python3
python.required = 3.9

[script:analysis_scope]
match = /analysis_scope
handler = analysis_scope.AnalysisScope
requireAuthentication = true
output_modes = json
python.version = python3
python.required = 3.9
