[datamodel_fields_lookup]
external_type = kvstore
collection = datamodel_fields
fields_list = _key, datamodel, table_index, field_name, notes, source_url, field_status, recommended, required, last_seen, updated_at

[cim_datamodel_tags_lookup]
external_type = kvstore
collection = cim_datamodel_tags
fields_list = _key, datamodel, expected_tag, tag_role, updated_at

[governance_datamodel_mapping_lookup]
filename = governance_datamodel_mapping_lookup.csv

[telemetry_timeliness_rules]
filename = telemetry_timeliness_rules.csv
